# docker-compose for test developpement
# don't deploy it in the production server

services:
  lssm-coliving-db:
    container_name: lssm-coliving-db
    image: postgres:15
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=lssm_coliving
      - POSTGRES_USER=lssm
      - POSTGRES_PASSWORD=lssm
      - PGDATA=/var/lib/lssm-coliving-db/data
    volumes:
      - ./configs/db-psql/init:/docker-entrypoint-initdb.d

  lssm-artisan-db:
    container_name: lssm-artisan-db
    image: postgres:15
    ports:
      - 5434:5432
    environment:
      - POSTGRES_DB=lssm_artisan
      - POSTGRES_USER=lssm
      - POSTGRES_PASSWORD=lssm
      - PGDATA=/var/lib/lssm-artisan-db/data
    volumes:
      - ./configs/db-psql/init:/docker-entrypoint-initdb.d
