[test]
root = "."
environment = "node"
preload = ["./src/__tests__/env-setup.ts", "./src/__tests__/preload.ts"]
coverage = false
coverageProvider = "v8"
coverageReporter = ["text"]
coverageExclude = ["**/*.test.ts", "**/__tests__/**"]
globals = true

[test.env]
CONTRACTSPEC_STUDIO_POSTGRES_PRISMA_URL = "postgresql://postgres:postgres@localhost:5432/studio"
